console.log ('datastore.js is connected')

const quizData =[{number:1, 
question:'In what movie was this said? "And Saint Attila raised the Hand Grenade up on high, saying, `O Lord, bless this Thy Hand Grenade that, with it, Thou mayest blow Thine enemies into tiny bits... in Thy mercy."', 
img:'',
alt:'',
answer1:"Constantine", 
answer2:"Passion of the Christ", 
answer3:"Holy Grail", 
answer4:"Life of Brian"},
{ number:2, question:'In what movie was this said? "...Hýn ú ortheri. Natha daged aen!"  "Then I shall die as one them!"',
img:'',
alt:'',
answer1: "Lord of the Rings: The Fellowship of the Ring", 
answer2: "Lord of the Rings: Two Towers",
answer3: "Lord of the Rings: Return of the King", 
answer4: "The Hobbit", }, 
{ number:3, question:'In what movie was this said? "Eat to bite... bite to eat, bite to eat, bite to eat, bitetoeat bitetoeat bitetoeatbitetoeatbitetoeatbitetoeat"', 
img:'',
alt:'',
answer1: "Borat", 
answer2: "As far as my feet will carry me",
answer3: "The terminal", 
answer4: "Lost in translation", }, 
{ number:4, question:'In what movie was this said? "By all means move at a glacial pace. You know how that thrills me."',
img:'',
alt:'',
answer1:"Pitch Perfect", 
answer2: "Iron man",
answer3: "Zoolander", 
answer4: "Devil wears prada", }, 
{ number:5, question:'In what movie was this said? "Do, or do not. There is no try."', 
img:'',
alt:'',
answer1: "Star Wars: A new hope", 
answer2: "Star Wars: Empire strikes back",
answer3: "Star Wars: Return of the Jedi", 
answer4: "Star Wars: Rogue One", }, 
{number:6, question:' What movie is this picture from?', img: 'https://i.redd.it/1mok11qzdbj11.jpg', 
alt:'Picture of Batman standing amongs rubble' 
answer1:"The Dark Knight", 
answer2:"Batman Begins", 
answer3:"Batman Forever", 
answer4:"Dark Knight Rises"},
{number:7, question:' What movie is this picture from?', img: 'https://cdntdreditorials.azureedge.net/cache/4/2/0/0/c/7/4200c7a223d20ee24bbee8a52e465f246e816b02.jpg', 
alt: 'Picture of cars and motercycles driving in a desert and a man playing a fire shooting guitar', 
answer1:"Death Proof", 
answer2:"Mad Max Fury Road", 
answer3:"Dawn of the Dead", 
answer4:"Mad Max Beyond Thunder Dome"},
{number:8, question:' What movie is this picture from?', img: 'https://earofnewtdotcom.files.wordpress.com/2013/12/1a900-the-hitcher-2007-gun.jpg', 
alt:'Picture of a man in the dirvers seat of a truck cab with a woman pointing a gun at him', 
answer1:"The Hitcher", 
answer2:"Hostage", 
answer3:"Silent Hill", 
answer4:"Randsome"},
{number:9, question:' What movie is this picture from?', img: 'https://www.truewestmagazine.com/wp-content/uploads/2013/07/michael-biehn-and-powers-boothe-post.jpg', 
alt:'Picture of two men in cowboy outfits in a saloon, one is pointing a gun the other is holding money', 
answer1:"The Shootist", 
answer2:"Wyatt Earp", 
answer3:"Tombstone", 
answer4:"My Darling Clementine"},
{number:10, question:' What movie is this picture from?', img: 'https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/youve-got-mail-1545164594.jpg', 
alt:'Picture of a man and woman sitting back to back in a cafe', 
answer1:"You've Got Mail", 
answer2:"Joe vs. the Volcano", 
answer3:"Sleepless in Seattle", 
answer4:"Catch Me if you can"},
];